// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mwttoqlcwypjlqgjkthq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13dHRvcWxjd3lwamxxZ2prdGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDk2NzUsImV4cCI6MjA2MjAyNTY3NX0.--cE9UQ_leUWsF4use_hi-bJscA0EZ0UPQHwcHLC-pM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);